# Add Configure button screen
screen = ACID_INTENSITY

# Label name in the menu
option.ACID_INTENSITY = Acid Intensity

# Tell OptiFine/Iris to render ACID_INTENSITY as a GUI Slider!
sliders = ACID_INTENSITY